blog/blog/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^main/', include('main.urls', namespace='main')),
    url(r'^article/', include('article.urls', namespace='article')),
    url(r'^.*', include('main.urls')),
]

blog/book/urls.py
from django.conf.urls import url
from article import views


urlpatterns = [
    url(r'^$', views.article, name='article'),
]

blog/main/urls.py
from django.conf.urls import url
from main import views

urlpatterns = [
    url(r'^$', views.main, name='main'),
    url(r'^about/$', views.about, name='about'),
    url(r'^contact/$', views.contact, name='contact')
]

blog/article/models.py
from django.db import models

# Create your models here.

blog/book/models.py
from django.db import models

class Article(models.Model):
    title = models.CharField(max_length=128, unique=True)
    content = models.TextField()
    pubDateTime = models.DateTimeField(auto_now_add=True)
    likes = models.IntegerField(default=0)
     
    def __str__(self):
        return self.title
    class Meta:
        ordering = ('-pubDateTime',)
     
class Comment(models.Model):
    article = models.ForeignKey(Article)
    content = models.CharField(max_length=128)
    pubDateTime = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.article.title + '-' + str(self.id)


class Book(models.Model):
    title = models.CharField(max_length=128,unique=True)
    author = models.CharField(max_length=128)
    publisher = models.CharField(max_length=128)
    pubDate = models.DateField()
    version = models.CharField(max_length=128)
    price = models.IntegerField()
    
    def __str__(self):
        return self.title

blog/main/models.py
from django.db import models

# Create your models here.

blog/article/views.py
from django.shortcuts import render

def article(request):
    '''
    Render the article page
    '''
    return render(request, 'article/article.html')

blog/book/views.py
from django.shortcuts import render

from article.models import Article, Comment

def article(request):
    '''
    Render the article page
    '''
    articles = Article.objects.all()
    itemArray = []
    for article in articles:
        items = [article]
        items.extend(list(Comment.objects.filter(article=article)))
        itemArray.append(items)
    context = {'itemArray':itemArray}
    return render(request, 'article/article.html',context)

blog/main/views.py
from django.shortcuts import render
import datetime

# Create your views here.
def main(request):
    '''
    Render the main page
    '''
    now = datetime.datetime.now()
    context = {'like':'Django 很棒','now':now}
    return render(request, 'main/main.html', context)
def about(request):
    '''
    Render the about page
    '''
    return render(request, 'main/about.html')
def contact(request):
    '''
    Render the about page
    '''
    return render(request, 'main/contact.html')

blog/article/templates/article/article.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>部落格</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'main/css/main.css' %}">
<link rel="stylesheet" href="{% static 'article/css/article.css' %}">
</head>
<body>
{% include 'main/menu.html' %}
<h1>歡迎來到我的部落格</h1>
<br>
{% for items in itemArray %}
	{% for item in items %}
	   {% if forloop.first %}
		 <h3>{{item.title }}</h3>
		 <p>發表時間:{{item.pubDateTime|date:'Y-m-d H:i' }}</p>
		 <div class=articleContent>{{item.content|linebreaks|truncatechars_html:30 }}</div>
		 <p>瀏覽次數:{{item.views }},按讚:{{item.likes }}</p>
	{% else %}
	   <p>
		   <span class=comment>{{item.content }}</span><br>
		   <span class=commentTime>{{item.pubDateTime|date:'m 月 d 日 H:i'}}</span>
	   </p>
	 {% endif %}
  {% endfor %}
	<hr>
{% endfor %}

<br>
</body>
</html>

blog/book/templates/book/book.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>部落格</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'main/css/main.css' %}">
<link rel="stylesheet" href="{% static 'article/css/article.css' %}">
</head>
<body>
{% include 'main/menu.html' %}
<h1>歡迎來到我的部落格</h1>
<br>
{% for article in articles %}
<h3>{{ article.title }}</h3>
	<p>發表時間:{{ article.pubDateTime|date:'Y-m-d H:i' }}</p>
	<div class=articleContent>{{ article.content }}</div>
	<p>瀏覽次數:{{ article.views }},按讚:{{ article.likes }}</p>
	<hr>
{% endfor %}

<br>
</body>
</html>

blog/main/templates/main/about.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>部落格</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'main/css/main.css' %}">
</head>
<body>
{% include 'main/menu.html' %}
<h1>關於</h1>
<p>歡迎來到我的部落格</p>
</body>
</html>

blog/main/templates/main/contact.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>部落格</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'main/css/main.css' %}">
</head>
<body>
{% include 'main/menu.html' %}
<h1>聯絡我們</h1>
</body>
</html>

blog/main/templates/main/main.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>部落格</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'main/css/main.css' %}">
</head>
<body>
{% include 'main/menu.html' %}
<h1>Django 說--Hello world!</h1>
<p>{{ like }}</p>
<p>現在時間:{{ now }}</p>
<br>
</body>
</html>

blog/main/templates/main/menu.html
<ul id="menu">
	<li><a href="{% url 'main:main' %}">首頁</a></li>
	<li><a href="{% url 'main:about' %}">關於</a></li>
	<li><a href="{% url 'article:article' %}">部落格</a></li>
	<li><a href="{% url 'main:contact' %}">聯絡我們</a></li>
</ul>